<?php
/**
 * Header file for guide theme.
 */
?><!DOCTYPE html>
<html class="no-js" <?php language_attributes(); ?>>

	<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
    	<!-- <script async src=""></script>
    	<script></script> -->
    <!-- Global site tag (gtag.js) - Google Analytics -->

		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<link rel="profile" href="https://gmpg.org/xfn/11">
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">

	<!-- Other meta tags should be set via Yoast SEO plugin -->

	<!-- Should not link stylesheets here // use wp_enqueue_script instead -->
		<link rel="stylesheet" href="<?php bloginfo('template_url'); ?>/css/bootstrap.min.css" />
    	<link rel="stylesheet" href="<?php bloginfo('template_url'); ?>/css/styles.css" />
	<!-- Should not link stylesheets here // use wp_enqueue_script instead -->

	<!-- wp_head generated by wp -->
		<?php wp_head(); ?>
	<!-- wp_head generated by wp -->
	</head>

	<body data-spy="scroll" data-target="#navbar" data-offset="120" <?php body_class(); ?>>

		<?php
		wp_body_open();
		?>

		<header id="site-header" class="header-footer-group" role="banner">

			<nav id="navbar" class="navbar fixed-top navbar-expand-sm navbar-dark bg-light">
				<div class="container">	

					<!-- Brand and toggle button -->
						<a class="navbar-brand" href="/guide-website-wp">
							<div>Wojciech Chrzastek<small class="font-weight-light"><br>Malaga guide</small></div>
						</a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
					<!-- End -->

					<!-- Website links -->
					<div class="collapse navbar-collapse justify-content-end" id="navbarNav">
						<div class="navbar-nav">
							<?php
								wp_nav_menu( array(
								'menu'              => 'primary',
								'theme_location'    => 'header-menu',
								'depth'             => 2,
								'container'         => 'div',
								'container_class'   => '',
								'container_id'      => '',
								'menu_class'        => 'navbar-nav mr-auto',
								'fallback_cb'       => 'wp_bootstrap_navwalker::fallback',
								'walker'            => new wp_bootstrap_navwalker())
								);
							?>
						</div>
					</div>
					<!-- End -->

				</div>
			</nav>

		</header>

		<button onclick="topFunction()" id="scrollButton" title="Scroll up"><i class="fas fa-angle-up"></i></button>
