<?php
/**
 * Header file for guide theme.
 */
?><!DOCTYPE html>
<html class="no-js" <?php language_attributes(); ?>>

	<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
    	<!-- <script async src=""></script>
    	<script></script> -->
    <!-- Global site tag (gtag.js) - Google Analytics -->

		<meta charset="<?php bloginfo( 'charset' ); ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<link rel="profile" href="https://gmpg.org/xfn/11">

	<!-- Should be set via wp -->
		<!-- <title><?php wp_title(); ?></title>
		<meta name="description" content="Guide wp-theme" />
		<meta name="keywords" content="guide wp-theme" />
   		<meta name="author" content="Wojciech Chrzastek" />
    	<meta name="copyright" content="Wojciech Chrzastek" />
    	<meta name="robots" content="index, follow" /> -->
	<!-- Should be set via wp -->

	<!-- Should not link stylesheets here // use wp_enqueue_script instead -->
		<link rel="stylesheet" href="<?php bloginfo('template_url'); ?>/css/bootstrap.min.css" />
    	<link rel="stylesheet" href="<?php bloginfo('template_url'); ?>/css/styles.css" />	
	<!-- Should not link stylesheets here // use wp_enqueue_script instead -->

	<!-- wp_head generated by wp -->
		<?php wp_head(); ?>
	<!-- wp_head generated by wp -->
	</head>

	<body data-spy="scroll" data-target="#navbar" data-offset="120" <?php body_class(); ?>>

		<?php
		wp_body_open();
		?>

		<header id="site-header" class="header-footer-group" role="banner">

			<nav id="navbar" class="navbar fixed-top navbar-expand-sm navbar-dark bg-light">
				<div class="container">
					<a class="navbar-brand" href="#top">
        		        <div>Wojciech Chrzastek<small class="font-weight-light"><br>Malaga guide</small></div>
        		    </a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        		        <span class="navbar-toggler-icon"></span>
        		    </button>
					<div class="collapse navbar-collapse justify-content-end" id="navbarNav">
						<div class="navbar-nav">
							<?php wp_nav_menu( array( 'theme_location' => 'header-menu' ) ); ?>
						</div>
					</div>
				</div>
			</nav>

		</header>
